<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>AegiNext.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="AegiNext.Application.Tests" />
    <ProjectReference Include="../AegiNext.Core/AegiNext.Core.csproj" />
  </ItemGroup>
</Project>
