<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>AegiNext.Rendering</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../AegiNext.Core/AegiNext.Core.csproj" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.HarfBuzz" />
  </ItemGroup>
</Project>
