<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>AegiNext.ExportWorker</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../AegiNext.Application/AegiNext.Application.csproj" />
    <ProjectReference Include="../AegiNext.Media/AegiNext.Media.csproj" />
  </ItemGroup>
</Project>
