<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>AegiNext.Desktop.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <ProjectReference Include="../../src/AegiNext.Desktop/AegiNext.Desktop.csproj" />
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../AegiNext.Rendering.Tests/Fixtures/NotoSans.ttf" Link="Fixtures/NotoSans.ttf" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../AegiNext.Rendering.Tests/Fixtures/NotoSans-OFL.txt" Link="Fixtures/NotoSans-OFL.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
