using System.Globalization;

namespace AegiNext.Desktop.Localization;

internal static class SettingsText
{
    private static readonly Dictionary<string, (string Chinese, string English)> entries = new(StringComparer.Ordinal)
    {
        ["Settings"] = ("设置", "Settings"),
        ["Appearance"] = ("外观与语言", "Appearance"),
        ["Colors"] = ("配色", "Colors"),
        ["AudioPalette"] = ("音频图配色方案", "Audio graph palette"),
        ["AudioPaletteHint"] = ("内置方案随深浅主题适配，自定义颜色保持原值。语谱图按能量显示低、中、高强度颜色；波形支持透明度。修改立即应用并保存为个人设置。", "Built-in palettes adapt to light and dark themes; custom colors stay unchanged. Spectrum colors represent low, medium and high energy. Waveform supports transparency. Changes apply immediately and are saved in personal settings."),
        ["AudioLow"] = ("低强度", "Low energy"),
        ["AudioMid"] = ("中强度", "Medium energy"),
        ["AudioHigh"] = ("高强度", "High energy"),
        ["AudioWaveform"] = ("波形", "Waveform"),
        ["AudioClassic"] = ("经典", "Classic"),
        ["AudioIce"] = ("冰蓝", "Ice"),
        ["AudioFire"] = ("暖焰", "Fire"),
        ["AudioGray"] = ("灰阶", "Grayscale"),
        ["AudioCustom"] = ("自定义", "Custom"),
        ["Shortcuts"] = ("快捷键", "Shortcuts"),
        ["Styles"] = ("字幕样式", "Subtitle styles"),
        ["Effects"] = ("特效脚本", "Effect scripts"),
        ["NewEffect"] = ("新特效", "New effect"),
        ["SaveEffectAs"] = ("另存为", "Save as"),
        ["BuiltinScriptReadOnly"] = ("内置脚本只读；另存为后可编辑。", "Built-in script is read-only. Save as a personal template to edit."),
        ["ScriptUnsaved"] = ("个人脚本 · 未保存", "Personal script · unsaved"),
        ["ScriptSaved"] = ("个人脚本 · 已保存", "Personal script · saved"),
        ["ScriptValid"] = ("语法与模板约束验证通过。", "Syntax and template validation passed."),
        ["ValidateScript"] = ("验证脚本", "Validate script"),
        ["RestoreDraft"] = ("恢复已保存内容", "Restore saved source"),
        ["LocateError"] = ("定位错误", "Go to error"),
        ["ScriptHintHeader"] = ("effect \"稳定标识\" version 1", "effect \"stable-id\" version 1"),
        ["ScriptHintCompress"] = ("片段过短时按比例压缩固定时间段。", "Compress fixed sections for short clips."),
        ["ScriptHintReject"] = ("拒绝比固定时间段总和更短的片段。", "Reject clips shorter than the fixed sections."),
        ["ScriptHintAt"] = ("at 段内比例 属性 数值 [插值方式]", "at progress property value [interpolation]"),
        ["ScriptHintEndpoints"] = ("每个动画属性从 0 开始并在 1 结束。", "Each animated property begins at 0 and ends at 1."),
        ["ScriptHintEnd"] = ("结束当前时间段。", "Close this segment."),
        ["ScriptHintFixed"] = ("固定时长，单位使用 s 或 ms。", "Fixed duration; seconds or milliseconds."),
        ["ScriptHintFlex"] = ("按权重分配片段的剩余时长。", "Share all remaining clip time using this weight."),
        ["ScriptHintVector"] = ("向量：(x, y)、base、offset(x, y)、factor(x, y)。", "Vector (x, y), base, offset(x, y), factor(x, y)"),
        ["ScriptHintScalar"] = ("标量：数值、base、offset(value)、factor(value)。", "Scalar, base, offset(value), factor(value)"),
        ["ScriptHintColor"] = ("线性颜色：rgba(r, g, b, a) 或 base；RGB 支持 HDR，Alpha 为 0 至 1。", "Linear color: rgba(r, g, b, a) or base; RGB supports HDR and alpha ranges from 0 to 1."),
        ["ScriptHintPath"] = ("路径进度 0 至 1，仅支持绝对数值。", "Path progress from 0 to 1; absolute values only."),
        ["ScriptHintBase"] = ("应用脚本前捕获的原始属性值。", "The property value before applying the script."),
        ["ScriptHintOffset"] = ("在原始属性值上增加偏移。", "Add to the captured base value."),
        ["ScriptHintFactor"] = ("将原始属性值乘以倍率。", "Multiply the captured base value."),
        ["ScriptHintAbsolute"] = ("绝对数值。", "Absolute value."),
        ["ScriptHintInterpolation"] = ("从当前关键帧到下一关键帧的插值。", "Interpolation from this keyframe to the next."),
        ["Effect_fade-in-out"] = ("淡入淡出", "Fade in and out"),
        ["Effect_fade-in"] = ("淡入", "Fade in"),
        ["Effect_fade-out"] = ("淡出", "Fade out"),
        ["Effect_pop-in"] = ("弹入", "Pop in"),
        ["Effect_pop-out"] = ("弹出", "Pop out"),
        ["Effect_slide-in"] = ("滑入", "Slide in"),
        ["Effect_slide-out"] = ("滑出", "Slide out"),
        ["Theme"] = ("外观", "Theme"),
        ["Accent"] = ("主色", "Accent color"),
        ["LinearRgba"] = ("线性 RGBA", "Linear RGBA"),
        ["HexValidation"] = ("请输入 #RRGGBB 或 #RRGGBBAA 格式的颜色；Esc 恢复原值。", "Enter #RRGGBB or #RRGGBBAA. Press Esc to restore the original value."),
        ["RgbaValidation"] = ("请输入四个 0–255 整数，以逗号分隔，例如 255,255,255,255；Esc 恢复原值。", "Enter four integers from 0 to 255, separated by commas, e.g. 255,255,255,255. Press Esc to restore the original value."),
        ["ColorInputMode"] = ("切换 HEX / RGBA 输入", "Switch HEX / RGBA input"),
        ["OpenColorPicker"] = ("打开取色框", "Open color picker"),
        ["ColorPreview"] = ("颜色预览", "Color preview"),
        ["LinearColorValidation"] = ("RGB 必须在 −65504 至 65504，Alpha 在 0 至 1；Esc 恢复该字段。", "RGB must be between −65504 and 65504; alpha between 0 and 1. Press Esc to restore this field."),
        ["Language"] = ("语言", "Language"),
        ["MenuLocation"] = ("菜单位置", "Menu location"),
        ["SystemMenu"] = ("系统菜单栏", "System menu bar"),
        ["WindowMenu"] = ("窗口标题栏", "Window title bar"),
        ["System"] = ("跟随系统", "System"),
        ["Light"] = ("浅色", "Light"),
        ["Dark"] = ("深色", "Dark"),
        ["Action"] = ("操作", "Action"),
        ["Gesture"] = ("按键", "Shortcut"),
        ["Record"] = ("录入按键", "Record keys"),
        ["Recording"] = ("请按快捷键…", "Press shortcut…"),
        ["ShortcutFormatValidation"] = ("快捷键格式无效，请重新录入按键。", "Invalid shortcut format. Record the keys again."),
        ["ShortcutConflictValidation"] = ("快捷键 {0} 已被“{1}”使用。", "Shortcut {0} is already assigned to “{1}”."),
        ["Clear"] = ("清除", "Clear"),
        ["Reset"] = ("恢复默认", "Restore defaults"),
        ["ResetAutomaticPosition"] = ("恢复自动位置", "Restore automatic position"),
        ["Save"] = ("保存", "Save"),
        ["Saved"] = ("已保存", "Saved"),
        ["Name"] = ("名称", "Name"),
        ["NewStyle"] = ("新样式", "New style"),
        ["CopySuffix"] = ("副本", "copy"),
        ["Add"] = ("新增", "Add"),
        ["Duplicate"] = ("复制", "Duplicate"),
        ["Delete"] = ("删除", "Delete"),
        ["Capture"] = ("从当前字幕获取", "Capture current subtitle"),
        ["Apply"] = ("应用到当前字幕", "Apply to current subtitle"),
        ["Import"] = ("导入", "Import"),
        ["Export"] = ("导出", "Export"),
        ["Font"] = ("字体", "Font family"),
        ["FontSize"] = ("字号", "Size"),
        ["SystemFont"] = ("系统字体", "System font"),
        ["EmbeddedFont"] = ("内嵌字体", "Embedded font"),
        ["Bold"] = ("粗体", "Bold"),
        ["Italic"] = ("斜体", "Italic"),
        ["Fill"] = ("文字颜色", "Text color"),
        ["Stroke"] = ("描边颜色", "Outline color"),
        ["StrokeWidth"] = ("描边宽度", "Outline width"),
        ["Alignment"] = ("对齐", "Alignment"),
        ["Margin"] = ("边距", "Margin"),
        ["ExplicitPosition"] = ("自定义锚点位置", "Custom anchored position"),
        ["AnchorPreset"] = ("锚点预设", "Anchor presets"),
        ["AnchorPresetHint"] = ("点击保留文字位置；Shift 同时设置轴心；Alt 将偏移归零。", "Click preserves the text position; Shift also sets the pivot; Alt resets offsets to zero."),
        ["SubtitlePositionHint"] = ("锚点相对画布，轴心相对实际文字。0 为左／上，1 为右／下；偏移单位为像素。", "Anchor follows the canvas; pivot follows the glyph bounds. 0 is left/top, 1 is right/bottom; offsets use pixels."),
        ["AnchorX"] = ("锚点 X", "Anchor X"), ["AnchorY"] = ("锚点 Y", "Anchor Y"),
        ["PivotX"] = ("轴心 X", "Pivot X"), ["PivotY"] = ("轴心 Y", "Pivot Y"),
        ["OffsetX"] = ("偏移 X（像素）", "Offset X (pixels)"), ["OffsetY"] = ("偏移 Y（像素）", "Offset Y (pixels)"),
        ["Advanced"] = ("排版与阴影", "Layout and shadow"),
        ["LineHeight"] = ("行高", "Line height"),
        ["ShadowX"] = ("阴影 X", "Shadow X"),
        ["ShadowY"] = ("阴影 Y", "Shadow Y"),
        ["ShadowBlur"] = ("阴影模糊", "Shadow blur"),
        ["ShadowColor"] = ("阴影颜色", "Shadow color"),
        ["EmptyStyles"] = ("暂无样式", "No styles yet"),
        ["NameRequired"] = ("请输入样式名称。", "Enter a style name."),
        ["DuplicateName"] = ("样式名称已存在。", "A style with this name already exists."),
        ["FontRequired"] = ("请输入字体名称。", "Enter a font family."),
        ["StyleValidation"] = ("样式字段无效，请检查名称、字体与数值。", "Invalid style. Check the name, font, and numeric fields."),
        ["TOP_LEFT"] = ("顶部左侧", "Top left"),
        ["TOP_CENTER"] = ("顶部居中", "Top center"),
        ["TOP_RIGHT"] = ("顶部右侧", "Top right"),
        ["MIDDLE_LEFT"] = ("中部左侧", "Middle left"),
        ["MIDDLE_CENTER"] = ("居中", "Center"),
        ["MIDDLE_RIGHT"] = ("中部右侧", "Middle right"),
        ["BOTTOM_LEFT"] = ("底部左侧", "Bottom left"),
        ["BOTTOM_CENTER"] = ("底部居中", "Bottom center"),
        ["BOTTOM_RIGHT"] = ("底部右侧", "Bottom right"),
        ["NEW_PROJECT"] = ("新建工程", "New project"),
        ["OPEN_PROJECT"] = ("打开工程", "Open project"),
        ["SAVE_PROJECT"] = ("保存工程", "Save project"),
        ["SAVE_PROJECT_AS"] = ("工程另存为", "Save project as"),
        ["OPEN_MEDIA"] = ("打开视频", "Open video"),
        ["IMPORT_SUBTITLES"] = ("导入字幕", "Import subtitles"),
        ["EXPORT_SUBTITLES"] = ("导出字幕", "Export subtitles"),
        ["UNDO"] = ("撤销", "Undo"),
        ["REDO"] = ("重做", "Redo"),
        ["OPEN_SETTINGS"] = ("打开设置", "Open settings"),
        ["PLAY_PAUSE"] = ("播放 / 暂停", "Play / pause"),
        ["SEEK_BACKWARD"] = ("后退五秒", "Back five seconds"),
        ["SEEK_FORWARD"] = ("前进五秒", "Forward five seconds"),
        ["TIMING_ENTER"] = ("打轴进入", "Set subtitle start"),
        ["TIMING_EXIT"] = ("打轴退出", "Set subtitle end"),
        ["ADD_SUBTITLE"] = ("新增字幕", "Add subtitle"),
        ["DELETE_SUBTITLE"] = ("删除字幕", "Delete subtitle"),
        ["SPLIT_SUBTITLE"] = ("拆分字幕", "Split subtitle"),
        ["MERGE_SUBTITLE"] = ("合并字幕", "Merge subtitles"),
        ["EXPORT_VIDEO"] = ("压制视频", "Encode video"),
        ["EXIT"] = ("退出", "Quit"),
        ["VIEW_STYLES"] = ("字幕样式面板", "Subtitle style panel"),
        ["VIEW_EFFECTS"] = ("特效面板", "Effects panel"),
        ["VIEW_EXPORT"] = ("压制面板", "Encode panel"),
        ["VIEW_TIMELINE"] = ("时间轴", "Timeline"),
        ["VIEW_PREVIEW"] = ("视频预览面板", "Video preview panel"),
        ["VIEW_SUBTITLES"] = ("字幕列表面板", "Subtitle list panel"),
        ["VIEW_LOG"] = ("日志面板", "Log panel"),
        ["LAYOUT_SAVE"] = ("保存布局", "Save layout"),
        ["LAYOUT_SAVE_AS"] = ("布局另存为", "Save layout as"),
        ["LAYOUT_MANAGE"] = ("管理布局", "Manage layouts"),
        ["LAYOUT_RESTORE_DEFAULT"] = ("恢复默认布局", "Restore default layout")
    };

    internal static string Get(string key)
    {
        var value = entries[key];
        return CultureInfo.CurrentUICulture.TwoLetterISOLanguageName == "zh" ? value.Chinese : value.English;
    }
}
