using System.Globalization;

namespace AegiNext.Desktop.Localization;

internal static class SettingsText
{
    private static readonly Dictionary<string, (string Chinese, string English)> entries = new(StringComparer.Ordinal)
    {
        ["Settings"] = ("设置", "Settings"),
        ["Appearance"] = ("外观与语言", "Appearance"),
        ["Shortcuts"] = ("快捷键", "Shortcuts"),
        ["Styles"] = ("字幕样式", "Subtitle styles"),
        ["Theme"] = ("外观", "Theme"),
        ["Accent"] = ("主色", "Accent color"),
        ["Language"] = ("语言", "Language"),
        ["MenuLocation"] = ("菜单位置", "Menu location"),
        ["SystemMenu"] = ("系统菜单栏", "System menu bar"),
        ["WindowMenu"] = ("窗口标题栏", "Window title bar"),
        ["System"] = ("跟随系统", "System"),
        ["Light"] = ("浅色", "Light"),
        ["Dark"] = ("深色", "Dark"),
        ["Action"] = ("操作", "Action"),
        ["Gesture"] = ("按键", "Shortcut"),
        ["Record"] = ("录入按键", "Record keys"),
        ["Recording"] = ("请按快捷键…", "Press shortcut…"),
        ["ShortcutValidation"] = ("快捷键格式无效或已被其他操作使用。", "Invalid shortcut or already assigned to another action."),
        ["Clear"] = ("清除", "Clear"),
        ["Reset"] = ("恢复默认", "Restore defaults"),
        ["Save"] = ("保存", "Save"),
        ["Saved"] = ("已保存", "Saved"),
        ["Name"] = ("名称", "Name"),
        ["NewStyle"] = ("新样式", "New style"),
        ["CopySuffix"] = ("副本", "copy"),
        ["Add"] = ("新增", "Add"),
        ["Duplicate"] = ("复制", "Duplicate"),
        ["Delete"] = ("删除", "Delete"),
        ["Capture"] = ("从当前字幕获取", "Capture current subtitle"),
        ["Apply"] = ("应用到当前字幕", "Apply to current subtitle"),
        ["Import"] = ("导入", "Import"),
        ["Export"] = ("导出", "Export"),
        ["Font"] = ("字体", "Font family"),
        ["FontSize"] = ("字号", "Size"),
        ["SystemFont"] = ("系统字体", "System font"),
        ["EmbeddedFont"] = ("内嵌字体", "Embedded font"),
        ["Bold"] = ("粗体", "Bold"),
        ["Italic"] = ("斜体", "Italic"),
        ["Fill"] = ("文字颜色", "Text color"),
        ["Stroke"] = ("描边颜色", "Outline color"),
        ["StrokeWidth"] = ("描边宽度", "Outline width"),
        ["Alignment"] = ("对齐", "Alignment"),
        ["Margin"] = ("边距", "Margin"),
        ["ExplicitPosition"] = ("自定义锚点位置", "Custom anchored position"),
        ["AnchorPreset"] = ("锚点预设", "Anchor presets"),
        ["AnchorPresetHint"] = ("点击保留文字位置；Shift 同时设置轴心；Alt 将偏移归零。", "Click preserves the text position; Shift also sets the pivot; Alt resets offsets to zero."),
        ["SubtitlePositionHint"] = ("锚点相对画布，轴心相对实际文字。0 为左／上，1 为右／下；偏移单位为像素。", "Anchor follows the canvas; pivot follows the glyph bounds. 0 is left/top, 1 is right/bottom; offsets use pixels."),
        ["AnchorX"] = ("锚点 X", "Anchor X"), ["AnchorY"] = ("锚点 Y", "Anchor Y"),
        ["PivotX"] = ("轴心 X", "Pivot X"), ["PivotY"] = ("轴心 Y", "Pivot Y"),
        ["OffsetX"] = ("偏移 X（像素）", "Offset X (pixels)"), ["OffsetY"] = ("偏移 Y（像素）", "Offset Y (pixels)"),
        ["Advanced"] = ("排版与阴影", "Layout and shadow"),
        ["LineHeight"] = ("行高", "Line height"),
        ["ShadowX"] = ("阴影 X", "Shadow X"),
        ["ShadowY"] = ("阴影 Y", "Shadow Y"),
        ["ShadowBlur"] = ("阴影模糊", "Shadow blur"),
        ["ShadowColor"] = ("阴影颜色", "Shadow color"),
        ["EmptyStyles"] = ("暂无样式", "No styles yet"),
        ["NameRequired"] = ("请输入样式名称。", "Enter a style name."),
        ["DuplicateName"] = ("样式名称已存在。", "A style with this name already exists."),
        ["FontRequired"] = ("请输入字体名称。", "Enter a font family."),
        ["StyleValidation"] = ("样式字段无效，请检查名称、字体与数值。", "Invalid style. Check the name, font, and numeric fields."),
        ["TOP_LEFT"] = ("顶部左侧", "Top left"),
        ["TOP_CENTER"] = ("顶部居中", "Top center"),
        ["TOP_RIGHT"] = ("顶部右侧", "Top right"),
        ["MIDDLE_LEFT"] = ("中部左侧", "Middle left"),
        ["MIDDLE_CENTER"] = ("居中", "Center"),
        ["MIDDLE_RIGHT"] = ("中部右侧", "Middle right"),
        ["BOTTOM_LEFT"] = ("底部左侧", "Bottom left"),
        ["BOTTOM_CENTER"] = ("底部居中", "Bottom center"),
        ["BOTTOM_RIGHT"] = ("底部右侧", "Bottom right"),
        ["NEW_PROJECT"] = ("新建工程", "New project"),
        ["OPEN_PROJECT"] = ("打开工程", "Open project"),
        ["SAVE_PROJECT"] = ("保存工程", "Save project"),
        ["SAVE_PROJECT_AS"] = ("工程另存为", "Save project as"),
        ["OPEN_MEDIA"] = ("打开视频", "Open video"),
        ["IMPORT_SUBTITLES"] = ("导入字幕", "Import subtitles"),
        ["EXPORT_SUBTITLES"] = ("导出字幕", "Export subtitles"),
        ["UNDO"] = ("撤销", "Undo"),
        ["REDO"] = ("重做", "Redo"),
        ["OPEN_SETTINGS"] = ("打开设置", "Open settings"),
        ["PLAY_PAUSE"] = ("播放 / 暂停", "Play / pause"),
        ["SEEK_BACKWARD"] = ("后退五秒", "Back five seconds"),
        ["SEEK_FORWARD"] = ("前进五秒", "Forward five seconds"),
        ["TIMING_ENTER"] = ("打轴进入", "Set subtitle start"),
        ["TIMING_EXIT"] = ("打轴退出", "Set subtitle end"),
        ["ADD_SUBTITLE"] = ("新增字幕", "Add subtitle"),
        ["DELETE_SUBTITLE"] = ("删除字幕", "Delete subtitle"),
        ["SPLIT_SUBTITLE"] = ("拆分字幕", "Split subtitle"),
        ["MERGE_SUBTITLE"] = ("合并字幕", "Merge subtitles"),
        ["EXPORT_VIDEO"] = ("压制视频", "Encode video"),
        ["EXIT"] = ("退出", "Quit"),
        ["VIEW_STYLES"] = ("字幕样式面板", "Subtitle style panel"),
        ["VIEW_EFFECTS"] = ("特效面板", "Effects panel"),
        ["VIEW_EXPORT"] = ("压制面板", "Encode panel"),
        ["VIEW_TIMELINE"] = ("时间轴", "Timeline"),
        ["VIEW_PREVIEW"] = ("视频预览面板", "Video preview panel"),
        ["VIEW_SUBTITLES"] = ("字幕列表面板", "Subtitle list panel"),
        ["VIEW_LOG"] = ("日志面板", "Log panel"),
        ["LAYOUT_SAVE"] = ("保存布局", "Save layout"),
        ["LAYOUT_SAVE_AS"] = ("布局另存为", "Save layout as"),
        ["LAYOUT_MANAGE"] = ("管理布局", "Manage layouts"),
        ["LAYOUT_RESTORE_DEFAULT"] = ("恢复默认布局", "Restore default layout")
    };

    internal static string Get(string key)
    {
        var value = entries[key];
        return CultureInfo.CurrentUICulture.TwoLetterISOLanguageName == "zh" ? value.Chinese : value.English;
    }
}
